name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  DEPLOY_MOBILE: false
  DEPLOY_WEB: true

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'

    - name: Install dependencies
      run: npm install

    - name: Run linting
      run: npm run lint

    - name: Install eas-cli
      run: npm install -g eas-cli

    - name: Login to EAS
      run: |
        echo "${{ secrets.EXPO_PASSWORD }}" | eas login ${{ secrets.EXPO_USERNAME }}
      if: ${{ env.DEPLOY_WEB == 'true' }}
      env:
        EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Build Android AAB with EAS
      run: |
        npx eas build --platform android --profile production --non-interactive
      if: ${{ env.DEPLOY_MOBILE == 'true' }}
      env:
        EXPO_USERNAME: ${{ secrets.EXPO_USERNAME }}
        EXPO_PASSWORD: ${{ secrets.EXPO_PASSWORD }}

    - name: Build web
      run: |
        npx expo export --platform web
      if: ${{ env.DEPLOY_WEB == 'true' }}

    - name: Deploy web
      run: |
        eas deploy --alias zeshanBaylorScott --non-interactive
      if: ${{ env.DEPLOY_WEB == 'true' }}
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
    - uses: actions/checkout@v3

    - name: Deploy to Expo
      run: |
        npx eas update --platform all
      if: ${{ env.DEPLOY_MOBILE == 'true' }}

